// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gqbimvaucbvbuupwvlof.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdxYmltdmF1Y2J2YnV1cHd2bG9mIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcxNTAzMzgsImV4cCI6MjA3MjcyNjMzOH0.xzP7CNYUaXR1lnwDAqSDYocp4Nt628d4hrZgPfO0hhI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});